# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConverterConfig.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_configScreen(object):
    def setupUi(self, configScreen):
        configScreen.setObjectName("configScreen")
        configScreen.resize(907, 492)
        self.nameDisplay = QtWidgets.QLabel(configScreen)
        self.nameDisplay.setGeometry(QtCore.QRect(0, 60, 81, 31))
        self.nameDisplay.setObjectName("nameDisplay")
        self.label_2 = QtWidgets.QLabel(configScreen)
        self.label_2.setGeometry(QtCore.QRect(600, 50, 191, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.destinationTable = QtWidgets.QTableWidget(configScreen)
        self.destinationTable.setGeometry(QtCore.QRect(580, 70, 301, 301))
        self.destinationTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.destinationTable.setColumnCount(4)
        self.destinationTable.setObjectName("destinationTable")
        self.destinationTable.setRowCount(0)
        self.destinationTable.horizontalHeader().setCascadingSectionResizes(True)
        self.destinationTable.horizontalHeader().setDefaultSectionSize(100)
        self.destinationTable.horizontalHeader().setStretchLastSection(True)
        self.saveSettingsButton = QtWidgets.QPushButton(configScreen)
        self.saveSettingsButton.setGeometry(QtCore.QRect(10, 454, 89, 31))
        self.saveSettingsButton.setObjectName("saveSettingsButton")
        self.cancelSettingsButton = QtWidgets.QPushButton(configScreen)
        self.cancelSettingsButton.setGeometry(QtCore.QRect(110, 454, 89, 31))
        self.cancelSettingsButton.setObjectName("cancelSettingsButton")
        self.openConfigButton = QtWidgets.QPushButton(configScreen)
        self.openConfigButton.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.openConfigButton.setObjectName("openConfigButton")
        self.createConfigButton = QtWidgets.QPushButton(configScreen)
        self.createConfigButton.setGeometry(QtCore.QRect(150, 10, 121, 31))
        self.createConfigButton.setObjectName("createConfigButton")
        self.addDestinationButton = QtWidgets.QPushButton(configScreen)
        self.addDestinationButton.setGeometry(QtCore.QRect(610, 380, 89, 25))
        self.addDestinationButton.setObjectName("addDestinationButton")
        self.removeDestinationButton = QtWidgets.QPushButton(configScreen)
        self.removeDestinationButton.setGeometry(QtCore.QRect(770, 380, 89, 25))
        self.removeDestinationButton.setObjectName("removeDestinationButton")
        self.label_3 = QtWidgets.QLabel(configScreen)
        self.label_3.setGeometry(QtCore.QRect(80, 180, 111, 17))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.enableAssociationButton = QtWidgets.QCheckBox(configScreen)
        self.enableAssociationButton.setGeometry(QtCore.QRect(60, 140, 151, 23))
        self.enableAssociationButton.setChecked(True)
        self.enableAssociationButton.setObjectName("enableAssociationButton")
        self.addAssociation = QtWidgets.QPushButton(configScreen)
        self.addAssociation.setGeometry(QtCore.QRect(270, 200, 51, 31))
        self.addAssociation.setObjectName("addAssociation")
        self.associationPreview = QtWidgets.QTableView(configScreen)
        self.associationPreview.setGeometry(QtCore.QRect(360, 100, 191, 271))
        self.associationPreview.setObjectName("associationPreview")
        self.label_4 = QtWidgets.QLabel(configScreen)
        self.label_4.setGeometry(QtCore.QRect(380, 80, 171, 20))
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.waterMarkDisplay = QtWidgets.QOpenGLWidget(configScreen)
        self.waterMarkDisplay.setGeometry(QtCore.QRect(10, 310, 121, 111))
        self.waterMarkDisplay.setObjectName("waterMarkDisplay")
        self.label_5 = QtWidgets.QLabel(configScreen)
        self.label_5.setGeometry(QtCore.QRect(60, 250, 141, 17))
        self.label_5.setObjectName("label_5")
        self.addWatermark = QtWidgets.QPushButton(configScreen)
        self.addWatermark.setGeometry(QtCore.QRect(270, 270, 51, 31))
        self.addWatermark.setObjectName("addWatermark")
        self.saveEventName_2 = QtWidgets.QPushButton(configScreen)
        self.saveEventName_2.setGeometry(QtCore.QRect(310, 60, 61, 31))
        self.saveEventName_2.setObjectName("saveEventName_2")
        self.associationPathDisplay = QtWidgets.QLabel(configScreen)
        self.associationPathDisplay.setGeometry(QtCore.QRect(10, 200, 251, 31))
        self.associationPathDisplay.setAutoFillBackground(True)
        self.associationPathDisplay.setFrameShape(QtWidgets.QFrame.Panel)
        self.associationPathDisplay.setText("")
        self.associationPathDisplay.setTextFormat(QtCore.Qt.PlainText)
        self.associationPathDisplay.setObjectName("associationPathDisplay")
        self.watermarkPathDisplay = QtWidgets.QLabel(configScreen)
        self.watermarkPathDisplay.setGeometry(QtCore.QRect(10, 270, 251, 31))
        self.watermarkPathDisplay.setAutoFillBackground(True)
        self.watermarkPathDisplay.setFrameShape(QtWidgets.QFrame.Panel)
        self.watermarkPathDisplay.setText("")
        self.watermarkPathDisplay.setTextFormat(QtCore.Qt.PlainText)
        self.watermarkPathDisplay.setObjectName("watermarkPathDisplay")
        self.showName = QtWidgets.QLineEdit(configScreen)
        self.showName.setGeometry(QtCore.QRect(90, 60, 211, 31))
        self.showName.setObjectName("showName")

        self.retranslateUi(configScreen)
        QtCore.QMetaObject.connectSlotsByName(configScreen)

    def retranslateUi(self, configScreen):
        _translate = QtCore.QCoreApplication.translate
        configScreen.setWindowTitle(_translate("configScreen", "Dialog"))
        self.nameDisplay.setText(_translate("configScreen", "Event Name"))
        self.label_2.setText(_translate("configScreen", "Destinations"))
        self.saveSettingsButton.setText(_translate("configScreen", "Save"))
        self.cancelSettingsButton.setText(_translate("configScreen", "Cancel"))
        self.openConfigButton.setText(_translate("configScreen", "Open File"))
        self.createConfigButton.setText(_translate("configScreen", "New File"))
        self.addDestinationButton.setText(_translate("configScreen", "Add"))
        self.removeDestinationButton.setText(_translate("configScreen", "Remove"))
        self.label_3.setText(_translate("configScreen", "Association List"))
        self.enableAssociationButton.setText(_translate("configScreen", "Enable Association"))
        self.addAssociation.setText(_translate("configScreen", "Add"))
        self.label_4.setText(_translate("configScreen", "Association Preview"))
        self.label_5.setText(_translate("configScreen", "Watermark Path"))
        self.addWatermark.setText(_translate("configScreen", "Add"))
        self.saveEventName_2.setText(_translate("configScreen", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    configScreen = QtWidgets.QDialog()
    ui = Ui_configScreen()
    ui.setupUi(configScreen)
    configScreen.show()
    sys.exit(app.exec_())
